CREATE COLUMN TABLE CATEGORIAS (
"CODIGODACATEGORIA" BIGINT NOT NULL,
"NOMEDACATEGORIA" VARCHAR(15) NOT NULL,
"DESCRICAO" VARCHAR(50) NOT NULL,
PRIMARY KEY (CODIGODACATEGORIA));

CREATE SEQUENCE CODIGODACATEGORIA START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE NO CACHE;
