CREATE COLUMN TABLE FORNECEDORES (
"CODIGODOFORNECEDOR" BIGINT NOT NULL,
"NOMEDAEMPRESA" VARCHAR(80) NOT NULL,
"NOMEDOCONTATO" VARCHAR(60) NOT NULL,
"CARGODOCONTATO" VARCHAR(60) NOT NULL,
"ENDERECO" VARCHAR(120) NOT NULL,
"CIDADE" VARCHAR(30) NOT NULL,
"REGIAO" VARCHAR(30),
"CEP" VARCHAR(20),
"PAIS" VARCHAR(30),
"TELEFONE" VARCHAR(48),
"FAX" VARCHAR(48),
"HOMEPAGE" VARCHAR(16),
PRIMARY KEY (CODIGODOFORNECEDOR));

CREATE SEQUENCE CODIGODOFORNECEDOR START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE NO CACHE;
