CREATE COLUMN TABLE PRODUTOS (
"CODIGODOPRODUTO" BIGINT NOT NULL,
"NOMEDOPRODUTO" VARCHAR(80) NOT NULL,
"CODIGODOFORNECEDOR" BIGINT NOT NULL,
"CODIGODACATEGORIA" BIGINT NOT NULL,
"QUANTIDADEPORUNIDADE" VARCHAR(50) NOT NULL,
"PRECOUNITARIO" DECIMAL NOT NULL,
"UNIDADESEMESTOQUE" SMALLINT,
"UNIDADESPEDIDAS" SMALLINT,
"NIVELDEREPOSICAO" SMALLINT,
"DESCONTINUADO" BOOLEAN,
PRIMARY KEY (CODIGODOPRODUTO));

CREATE SEQUENCE CODIGODOPRODUTO START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE NO CACHE;
